kind: ConfigMap
apiVersion: v1
metadata:
  name: pg-0
  namespace: demo
data:
  REPMGR_NODE_ID: "0"
  POSTGRESQL_USERNAME: user
  REPMGR_NODE_NAME: pg-0
  POSTGRESQL_DATABASE: database
  POSTGRESQL_PASSWORD: password
  REPMGR_PRIMARY_HOST: pg-0.demo.svc.clusterset.local
  REPMGR_NODE_NETWORK_NAME: pg-0.demo.svc.clusterset.local
  POSTGRESQL_POSTGRES_PASSWORD: password
  REPMGR_PARTNER_NODES: "pg-0.demo.svc.clusterset.local,pg-1.demo.svc.clusterset.local"
  REPMGR_PASSWORD: repmgrpass
