apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg0
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg0
  template:
    metadata:
      labels:
        app: pg0
        deployment: pg0
    spec:
      containers:
        - name: pg0
          image: >-
            image-registry.openshift-image-registry.svc:5000/demo/pg:latest
          ports:
            - containerPort: 5432
              protocol: TCP
          envFrom:
            - configMapRef:
                name: pg0
          resources: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
