kind: Deployment
apiVersion: apps/v1
metadata:
  name: pg-0
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-0
  template:
    metadata:
      labels:
        app: pg-0
        deployment: pg-0
    spec:
      containers:
        - name: pg-0
          image: >-
            image-registry.openshift-image-registry.svc:5000/demo/pg:latest
          ports:
            - containerPort: 5432
              protocol: TCP
          envFrom:
            - configMapRef:
                name: pg-0
          resources: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
