apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre-0
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgre-0
  template:
    metadata:
      labels:
        app: postgre-0
        deployment: postgre-0
    spec:
      containers:
        - name: postgre-0
          image: >-
            image-registry.openshift-image-registry.svc:5000/demo/pg:latest
          ports:
            - containerPort: 5432
              protocol: TCP
          envFrom:
            - configMapRef:
                name: postgre-0
          resources: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
