kind: Service
apiVersion: v1
metadata:
  name: pg0
  namespace: demo
spec:
  ports:
    - name: 5432-tcp
      protocol: TCP
      port: 5432
      targetPort: 5432
  internalTrafficPolicy: Cluster
  type: ClusterIP
  selector:
    app: pg0
    deployment: pg0
