kind: ConfigMap
apiVersion: v1
metadata:
  name: pgpool
  namespace: demo
immutable: false
data:
  PGPOOL_USERNAME: user
  PGPOOL_SR_CHECK_PASSWORD: password
  PGPOOL_PASSWORD: password
  PGPOOL_POSTGRES_USERNAME: postgres
  PGPOOL_ADMIN_USERNAME: postgres
  PGPOOL_POSTGRES_PASSWORD: password
  PGPOOL_SR_CHECK_USER: postgres
  PGPOOL_ADMIN_PASSWORD: password
  PGPOOL_ENABLE_LDAP: "no"
  PGPOOL_BACKEND_NODES: "0:postgre-0:5432,1:postgre-1:5432"
