kind: Deployment
apiVersion: apps/v1
metadata:
  name: pgpool
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgpool
  template:
    metadata:
      labels:
        app: pgpool
        deployment: pgpool
    spec:
      containers:
        - name: pgpool
          image: >-
            image-registry.openshift-image-registry.svc:5000/demo/pgpool@sha256:4fe526bc8e2fc9d74501baf8e023fc7ce65678fde1f351a79e28d9173d1f93cc
          ports:
            - containerPort: 5432
              protocol: TCP
          envFrom:
            - configMapRef:
                name: pgpool
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600      