kind: ConfigMap
apiVersion: v1
metadata:
  name: pg1
  namespace: demo
data:
  REPMGR_NODE_ID: "1"
  POSTGRESQL_USERNAME: user
  REPMGR_NODE_NAME: cluster4.pg1.demo.svc.clusterset.local
  POSTGRESQL_DATABASE: database
  POSTGRESQL_PASSWORD: password
  REPMGR_PRIMARY_HOST: cluster2.pg0.demo.svc.clusterset.local
  REPMGR_NODE_NETWORK_NAME: pg1.demo.svc.clusterset.local
  POSTGRESQL_POSTGRES_PASSWORD: password
  REPMGR_PARTNER_NODES: "pg0,pg1"
  REPMGR_PASSWORD: repmgrpass
