kind: Deployment
apiVersion: apps/v1
metadata:
  name: pg-1
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-1
  template:
    metadata:
      labels:
        app: pg-1
        deployment: pg-1
    spec:
      containers:
        - name: pg-1
          image: >-
            image-registry.openshift-image-registry.svc:5000/demo/pg:latest
          ports:
            - containerPort: 5432
              protocol: TCP
          envFrom:
            - configMapRef:
                name: pg-1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
